### PR TITLE
add support more then one extension

### PR DESCRIPTION
**Pull request by Sigura**
Hello Vu!

First, thank you for your work!

I try to add source-map to dev build and need to support more then one extension.

Please add this little changes.

### CODE REVIEW

**Comment by iOliverNguyen** [comment]
Thank you for your pull request.

Just a note, I'm currently using Webpack instead of gulp. If you have not used Webpack before, I strongly recommend to try it.

**Comment by Sigura** [comment]
I used webpack only as dev server for hot react component reload (with gulp).

I'm no thinking about using webpack instead.

You have a public sample? Or may be you will recommended me article?

Anyway thank you!

**Comment by iOliverNguyen** [comment]
Take a look at this one: [erikras/react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example).

The boilerplate has React, Redux, Webpack and many best practices for Universal Javascript application.

**Comment by Sigura** [comment]
Cool thank you!

**Pull request merged**
